version: '3'
services:
  php-nginx:
    build: ./
    image: lightkurve-website
    restart: always
    ports:
      - "80:80"
      - "8888:8888"
    volumes:
      - ./log/nginx:/var/log/nginx
      - ./log/cleanup:/var/log/cleanup
      - ./:/var/www/html